### ISSUE TITLE
Thumbnail qality is very low

### ISSUE THREAD

**Issue by arcsales** [Towhidn/Q2A-Infinity-Theme#2]
Is there any way we could improve the quality of thumbnail images?

**Comment by TohidN** [comment]
you can find and edit the thumbnail  quality by searching `$quality = 100;` in `ajax_upload.php` file in theme directory([here](https://github.com/q2a-projects/Q2A-Infinity-Theme/blob/master/Infinity-Theme/ajax_upload.php#L76)) and changing 100(for max quality) to a lower number, for example `50`. 
I will add an option for this in a future update.

**Comment by arcsales** [comment]
I did play with it before my post here but it appear that 100 is not enough.
May be im not using the right size or resolution images?
Could you please suggest what are the best height and width of images?

**Comment by TohidN** [comment]
I've used PHP's [GD and Image Functions](http://php.net/manual/en/ref.image.php) to resize the images and get thumbnail, and I didn't face any problems regarding thumbnail quality. but if you know PHP you can replace it with other libraries too get better results.

**Comment by arcsales** [comment]
Unfortunately my php knowledge is not enough to do anything about the thumbnail quality.
Could you take a look at my thumbnails? May be im not using the right dimensions.
![2](https://cloud.githubusercontent.com/assets/7887145/25075166/c227e57c-2316-11e7-919c-177eb7172145.PNG)
![1](https://cloud.githubusercontent.com/assets/7887145/25075165/c2264b2c-2316-11e7-90bd-3ede0bb223b2.PNG)
